spring:
 application:
  name: springbatchapp
 datasource:
  url: jdbc:postgresql://localhost:5432/file-upload
  username: deor
  password: deor
 jpa:
  hibernate:
   ddl-auto: create-drop
  show-sql: false
  properties:
   hibernate:
    format_sql: true  
  database: postgresql
  database-platform: org.hibernate.dialect.PostgreSQLDialect
 batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

server:
  port: 9090